name: yumio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  #  Flutter version 3.29.0
  #  Dart version 3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  carousel_slider: ^5.1.1
  device_preview: ^1.2.0
  delightful_toast: ^1.1.0
  pin_code_fields: ^8.0.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/logos/app_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/onboarding/
    - assets/others/shape/
    - assets/icons/common/
    - assets/icons/bottom_navigation/raw/
    - assets/icons/bottom_navigation/solid/
    - assets/images/avatar/
    - assets/images/category_chips/
    - assets/others/frame/
    - assets/images/categories/
    - assets/images/recipes/
    - assets/images/others/
    - assets/icons/drawer/
    - assets/icons/end_drawer/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-All-Font.ttf
        - asset: assets/fonts/DMSans-Extra-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Italic-Font.ttf
          style: italic

#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700

